apiVersion: v1
kind: Service
metadata:
  name: {{ printf `{{ include "%s.fullname" . }}` .ChartName }}
  labels:
    {{ printf `{{- include "%s.labels" . | nindent 4 }}` .ChartName }}
spec:
  type: {{ `{{ .Values.service.type }}` }}
  selector:
    app.kubernetes.io/name: {{ printf `{{ include "%s.name" . }}` .ChartName }}
    app.kubernetes.io/instance: {{ `{{ .Release.Name }}` }}
  ports:
    - port: {{ `{{ .Values.service.port }}` }}
      targetPort: {{ `{{ .Values.service.targetPort }}` }}
      protocol: TCP
      name: http
